apiVersion: v1
kind: Pod
metadata:
  name: snowflake-app
spec:
  containers:
    - name: snowflake-app
      image: snowflake-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
